# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'machine_marking.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_select = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select.setGeometry(QtCore.QRect(620, 100, 93, 28))
        self.pushButton_select.setObjectName("pushButton_select")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 160, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 80, 531, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 161, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionmanual_marking = QtWidgets.QAction(MainWindow)
        self.actionmanual_marking.setObjectName("actionmanual_marking")
        self.actionmachine_marking = QtWidgets.QAction(MainWindow)
        self.actionmachine_marking.setObjectName("actionmachine_marking")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.action_analy = QtWidgets.QAction(MainWindow)
        self.action_analy.setObjectName("action_analy")
        self.actionpre_making = QtWidgets.QAction(MainWindow)
        self.actionpre_making.setObjectName("actionpre_making")
        self.menu.addAction(self.actionmanual_marking)
        self.menu.addAction(self.actionmachine_marking)
        self.menu.addAction(self.action_analy)
        self.menu.addAction(self.actionpre_making)
        self.menu_2.addAction(self.actionhelp)
        self.menu_2.addAction(self.actionabout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_select.setText(_translate("MainWindow", "选择文件库"))
        self.pushButton.setText(_translate("MainWindow", "一键标注"))
        self.label.setText(_translate("MainWindow", "查看标注结果："))
        self.menu.setTitle(_translate("MainWindow", "&菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "&说明"))
        self.actionmanual_marking.setText(_translate("MainWindow", "welcome_window"))
        self.actionmachine_marking.setText(_translate("MainWindow", "manual_marking"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.action_analy.setText(_translate("MainWindow", "analy"))
        self.actionpre_making.setText(_translate("MainWindow", "pre_making"))
