# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_marking.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1395, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hereIsVideo = QtWidgets.QLabel(self.centralwidget)
        self.hereIsVideo.setGeometry(QtCore.QRect(290, 20, 881, 641))
        self.hereIsVideo.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.hereIsVideo.setText("")
        self.hereIsVideo.setObjectName("hereIsVideo")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1200, 50, 160, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.isAnger = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isAnger.setObjectName("isAnger")
        self.verticalLayout.addWidget(self.isAnger)

        self.isDisgust = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isDisgust.setObjectName("isDisgust")
        self.verticalLayout.addWidget(self.isDisgust)

        self.isFear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isFear.setObjectName("isFear")
        self.verticalLayout.addWidget(self.isFear)

        self.isHappy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isHappy.setObjectName("isHappy")
        self.verticalLayout.addWidget(self.isHappy)

        self.isSurprise = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isSurprise.setObjectName("isSurprise")
        self.verticalLayout.addWidget(self.isSurprise)

        self.isSad = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isSad.setObjectName("isSad")
        self.verticalLayout.addWidget(self.isSad)

        self.isNeutral = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isNeutral.setObjectName("isNeutral")
        self.verticalLayout.addWidget(self.isNeutral)

        self.isUnknow = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.isUnknow.setObjectName("isUnknow")
        self.verticalLayout.addWidget(self.isUnknow)

        self.subVideo = QtWidgets.QPushButton(self.centralwidget)
        self.subVideo.setGeometry(QtCore.QRect(1200, 720, 171, 31))
        self.subVideo.setObjectName("subVideo")

        self.machine_reg = QtWidgets.QPushButton(self.centralwidget)
        self.machine_reg.setGeometry(QtCore.QRect(1200, 760, 171, 31))
        self.machine_reg.setObjectName("machine_reg")

        self.selectVideo = QtWidgets.QPushButton(self.centralwidget)
        self.selectVideo.setGeometry(QtCore.QRect(10, 20, 251, 31))
        self.selectVideo.setObjectName("selectVideo")
        self.videoSlider = QtWidgets.QSlider(self.centralwidget)
        self.videoSlider.setGeometry(QtCore.QRect(280, 670, 891, 31))
        self.videoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoSlider.setObjectName("videoSlider")
        self.frameNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.frameNumber.setGeometry(QtCore.QRect(1100, 710, 71, 41))
        self.frameNumber.setObjectName("frameNumber")
        self.pauseVideoB = QtWidgets.QPushButton(self.centralwidget)
        self.pauseVideoB.setGeometry(QtCore.QRect(720, 720, 111, 31))
        self.pauseVideoB.setObjectName("pauseVideoB")
        self.nextVideoB = QtWidgets.QPushButton(self.centralwidget)
        self.nextVideoB.setGeometry(QtCore.QRect(860, 720, 111, 31))
        self.nextVideoB.setObjectName("nextVideoB")
        self.playVideoB = QtWidgets.QPushButton(self.centralwidget)
        self.playVideoB.setGeometry(QtCore.QRect(570, 720, 111, 31))
        self.playVideoB.setObjectName("playVideoB")
        self.preVideoB = QtWidgets.QPushButton(self.centralwidget)
        self.preVideoB.setGeometry(QtCore.QRect(420, 720, 111, 31))
        self.preVideoB.setObjectName("preVideoB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.backToWelcome = QtWidgets.QAction(MainWindow)
        self.backToWelcome.setObjectName("backToWelcome")
        self.backToMachine = QtWidgets.QAction(MainWindow)
        self.backToMachine.setObjectName("backToMachine")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.backToAnalysis = QtWidgets.QAction(MainWindow)
        self.backToAnalysis.setObjectName("backToAnalysis")
        self.backToPre = QtWidgets.QAction(MainWindow)
        self.backToPre.setObjectName("backToPre")

        #列表框
        self.play_list = QtWidgets.QListWidget(self.centralwidget)
        self.play_list.setGeometry(QtCore.QRect(10, 90, 251, 661))
        self.play_list.setObjectName("play_list")

        self.mark_list = QtWidgets.QListWidget(self.centralwidget)
        self.mark_list.setGeometry(QtCore.QRect(1200, 530, 171, 171))
        self.mark_list.setObjectName("mark_list")

        self.menu.addAction(self.backToWelcome)
        self.menu.addAction(self.backToMachine)
        self.menu.addAction(self.backToAnalysis)
        self.menu.addAction(self.backToPre)
        self.menu_2.addAction(self.actionhelp)
        self.menu_2.addAction(self.actionabout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1200, 500, 141, 21))
        self.label_2.setObjectName("label_2")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1200, 20, 211, 31))
        self.label.setObjectName("label")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1040, 710, 51, 41))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.isAnger.setText(_translate("MainWindow", "Anger"))
        self.isDisgust.setText(_translate("MainWindow", "Disgust"))
        self.isFear.setText(_translate("MainWindow", "Fear"))
        self.isHappy.setText(_translate("MainWindow", "Happy"))
        self.isSurprise.setText(_translate("MainWindow", "Surprise"))
        self.isSad.setText(_translate("MainWindow", "Sad"))
        self.isNeutral.setText(_translate("MainWindow", "Neutral"))
        self.isUnknow.setText(_translate("MainWindow", "Unknown"))
        self.subVideo.setText(_translate("MainWindow", "提交"))
        self.selectVideo.setText(_translate("MainWindow", "选择视频库"))
        self.pauseVideoB.setText(_translate("MainWindow", "暂停"))
        self.nextVideoB.setText(_translate("MainWindow", "下一条"))
        self.playVideoB.setText(_translate("MainWindow", "播放"))
        self.preVideoB.setText(_translate("MainWindow", "上一条"))
        self.menu.setTitle(_translate("MainWindow", "&菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "&说明"))
        self.backToWelcome.setText(_translate("MainWindow", "welcome_window"))
        self.backToMachine.setText(_translate("MainWindow", "machine_marking"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.backToAnalysis.setText(_translate("MainWindow", "analysis"))
        self.backToPre.setText(_translate("MainWindow", "pre_making"))
        self.label.setText(_translate("Manual", "选择标签"))
        self.label_2.setText(_translate("Manual", "标记结果："))
        self.label_3.setText(_translate("Manual", "当前帧"))
        self.label_4.setText(_translate("Manual", "当前播放列表"))
        self.machine_reg.setText(_translate("MainWindow", "机器标注"))