# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'premaking.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionwelcome_window = QtWidgets.QAction(MainWindow)
        self.actionwelcome_window.setObjectName("actionwelcome_window")
        self.actionmanual_marking = QtWidgets.QAction(MainWindow)
        self.actionmanual_marking.setObjectName("actionmanual_marking")
        self.actionmachine_marking = QtWidgets.QAction(MainWindow)
        self.actionmachine_marking.setObjectName("actionmachine_marking")
        self.actionanalysis_window = QtWidgets.QAction(MainWindow)
        self.actionanalysis_window.setObjectName("actionanalysis_window")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionauto = QtWidgets.QAction(MainWindow)
        self.actionauto.setObjectName("actionauto")
        self.actionman = QtWidgets.QAction(MainWindow)
        self.actionman.setObjectName("actionman")
        self.menu.addAction(self.actionwelcome_window)
        self.menu.addAction(self.actionmanual_marking)
        self.menu.addAction(self.actionmachine_marking)
        self.menu.addAction(self.actionanalysis_window)
        self.menu_2.addAction(self.actionhelp)
        self.menu_2.addAction(self.actionabout)
        self.menu_3.addAction(self.actionauto)
        self.menu_3.addAction(self.actionman)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "&菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "&说明"))
        self.menu_3.setTitle(_translate("MainWindow", "&模式选择"))
        self.actionwelcome_window.setText(_translate("MainWindow", "welcome_window"))
        self.actionmanual_marking.setText(_translate("MainWindow", "manual_marking"))
        self.actionmachine_marking.setText(_translate("MainWindow", "machine_marking"))
        self.actionanalysis_window.setText(_translate("MainWindow", "analysis_window"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionauto.setText(_translate("MainWindow", "auto"))
        self.actionman.setText(_translate("MainWindow", "man"))
