# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 140, 251, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_wel_man = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_wel_man.setObjectName("pushButton_wel_man")
        self.verticalLayout.addWidget(self.pushButton_wel_man)
        self.pushButton_wel_mac = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_wel_mac.setObjectName("pushButton_wel_mac")
        self.verticalLayout.addWidget(self.pushButton_wel_mac)
        self.pushButton_wel_ana = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_wel_ana.setObjectName("pushButton_wel_ana")
        self.verticalLayout.addWidget(self.pushButton_wel_ana)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 50, 501, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 26))
        self.menubar.setObjectName("menubar")
        self.menu_mode_select = QtWidgets.QMenu(self.menubar)
        self.menu_mode_select.setObjectName("menu_mode_select")
        self.menu_note = QtWidgets.QMenu(self.menubar)
        self.menu_note.setObjectName("menu_note")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionmanual_marking = QtWidgets.QAction(MainWindow)
        self.actionmanual_marking.setObjectName("actionmanual_marking")
        self.actionmachine_marking = QtWidgets.QAction(MainWindow)
        self.actionmachine_marking.setObjectName("actionmachine_marking")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionanalysis = QtWidgets.QAction(MainWindow)
        self.actionanalysis.setObjectName("actionanalysis")
        self.actionpre_deal = QtWidgets.QAction(MainWindow)
        self.actionpre_deal.setObjectName("actionpre_deal")
        self.menu_mode_select.addAction(self.actionmanual_marking)
        self.menu_mode_select.addAction(self.actionmachine_marking)
        self.menu_mode_select.addAction(self.actionanalysis)
        self.menu_mode_select.addAction(self.actionpre_deal)
        self.menu_note.addAction(self.actionhelp)
        self.menu_note.addAction(self.actionabout)
        self.menubar.addAction(self.menu_mode_select.menuAction())
        self.menubar.addAction(self.menu_note.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_wel_man.setText(_translate("MainWindow", "人工识别"))
        self.pushButton_wel_mac.setText(_translate("MainWindow", "机器识别"))
        self.pushButton_wel_ana.setText(_translate("MainWindow", "数据分析"))
        self.pushButton.setText(_translate("MainWindow", "数据预处理"))
        self.label.setText(_translate("MainWindow", "欢 迎 使 用 本 标 注 系 统 "))
        self.menu_mode_select.setTitle(_translate("MainWindow", "&菜单"))
        self.menu_note.setTitle(_translate("MainWindow", "&说明"))
        self.actionmanual_marking.setText(_translate("MainWindow", "manual_marking"))
        self.actionmachine_marking.setText(_translate("MainWindow", "machine_marking"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionanalysis.setText(_translate("MainWindow", "analysis"))
        self.actionpre_deal.setText(_translate("MainWindow", "pre_making"))
